# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
# created-by: conda 24.11.0
@EXPLICIT
https://repo.anaconda.com/pkgs/main/win-64/_tflow_select-2.3.0-mkl.conda
https://conda.anaconda.org/conda-forge/win-64/ca-certificates-2025.1.31-h56e8100_0.conda
https://conda.anaconda.org/conda-forge/win-64/intel-openmp-2024.2.1-h57928b3_1083.conda
https://conda.anaconda.org/conda-forge/win-64/python_abi-3.9-5_cp39.conda
https://repo.anaconda.com/pkgs/main/noarch/tzdata-2025a-h04d1e81_0.conda
https://conda.anaconda.org/conda-forge/win-64/ucrt-10.0.22621.0-h57928b3_1.conda
https://repo.anaconda.com/pkgs/main/win-64/winpty-0.4.3-4.conda
https://conda.anaconda.org/conda-forge/win-64/libwinpthread-12.0.0.r4.gg4f2fc60ca-h57928b3_9.conda
https://conda.anaconda.org/conda-forge/win-64/vc14_runtime-14.42.34433-h6356254_24.conda
https://conda.anaconda.org/conda-forge/win-64/vs2015_runtime-14.42.34433-hfef2bbc_24.conda
https://repo.anaconda.com/pkgs/main/win-64/vc-14.42-haa95532_4.conda
https://conda.anaconda.org/conda-forge/win-64/bzip2-1.0.8-h2466b09_7.conda
https://conda.anaconda.org/conda-forge/win-64/c-ares-1.34.4-h2466b09_0.conda
https://conda.anaconda.org/conda-forge/win-64/cudatoolkit-11.2.2-h7d7167e_13.conda
https://conda.anaconda.org/conda-forge/win-64/flatbuffers-25.1.21-hc4e18a8_0.conda
https://conda.anaconda.org/conda-forge/win-64/giflib-5.2.2-h64bf75a_0.conda
https://repo.anaconda.com/pkgs/main/win-64/icu-58.2-ha925a31_3.conda
https://conda.anaconda.org/conda-forge/win-64/jpeg-9e-hcfcfb64_3.conda
https://conda.anaconda.org/conda-forge/win-64/libabseil-20220623.0-cxx17_h1a56200_6.conda
https://conda.anaconda.org/conda-forge/win-64/libaec-1.1.3-h63175ca_0.conda
https://conda.anaconda.org/conda-forge/win-64/libffi-3.4.6-h537db12_0.conda
https://conda.anaconda.org/conda-forge/win-64/libiconv-1.17-hcfcfb64_2.conda
https://conda.anaconda.org/conda-forge/win-64/liblzma-5.6.4-h2466b09_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libsodium-1.0.18-h62dcd97_0.conda
https://conda.anaconda.org/conda-forge/win-64/libsqlite-3.48.0-h67fdade_1.conda
https://conda.anaconda.org/conda-forge/win-64/libzlib-1.2.13-h2466b09_6.conda
https://repo.anaconda.com/pkgs/main/win-64/openssl-1.1.1w-h2bbff1b_0.conda
https://conda.anaconda.org/conda-forge/win-64/re2-2022.06.01-h0e60522_1.conda
https://conda.anaconda.org/conda-forge/win-64/snappy-1.2.1-h500f7fa_1.conda
https://repo.anaconda.com/pkgs/main/win-64/sqlite-3.45.3-h2bbff1b_0.conda
https://conda.anaconda.org/conda-forge/win-64/tk-8.6.13-h5226925_1.conda
https://repo.anaconda.com/pkgs/main/win-64/yaml-0.2.5-he774522_0.conda
https://conda.anaconda.org/conda-forge/win-64/cudnn-8.1.0.77-h3e0f4f4_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/krb5-1.20.1-h6609f42_0.conda
https://conda.anaconda.org/conda-forge/win-64/liblzma-devel-5.6.4-h2466b09_0.conda
https://conda.anaconda.org/conda-forge/win-64/libpng-1.6.43-h19919ed_0.conda
https://conda.anaconda.org/conda-forge/win-64/libprotobuf-3.20.3-h12be248_0.conda
https://conda.anaconda.org/conda-forge/win-64/libssh2-1.10.0-h680486a_3.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/xz-tools-5.6.4-h2466b09_0.conda
https://repo.anaconda.com/pkgs/main/win-64/zeromq-4.3.5-hd77b12b_0.conda
https://conda.anaconda.org/conda-forge/win-64/zlib-1.2.13-h2466b09_6.conda
https://conda.anaconda.org/conda-forge/win-64/zstd-1.5.6-h0ea2cb4_0.conda
https://conda.anaconda.org/conda-forge/win-64/grpc-cpp-1.48.1-hcb02dd0_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/libclang13-14.0.6-default_h8e68704_2.conda
https://conda.anaconda.org/conda-forge/win-64/libcurl-8.1.2-h68f0423_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libpq-12.15-hb652d5d_1.conda
https://repo.anaconda.com/pkgs/main/win-64/libxml2-2.13.5-h24da03e_0.conda
https://conda.anaconda.org/conda-forge/win-64/xz-5.6.4-h208afaa_0.conda
https://conda.anaconda.org/conda-forge/win-64/hdf5-1.14.0-nompi_h97a5375_103.conda
https://repo.anaconda.com/pkgs/main/win-64/libclang-14.0.6-default_hb5a9fac_2.conda
https://conda.anaconda.org/conda-forge/win-64/libhwloc-2.11.2-default_ha69328c_1001.conda
https://conda.anaconda.org/conda-forge/win-64/python-3.9.15-h0269646_0_cpython.conda
https://conda.anaconda.org/conda-forge/noarch/absl-py-2.1.0-pyhd8ed1ab_1.conda
https://conda.anaconda.org/conda-forge/noarch/aiohappyeyeballs-2.4.6-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/async-timeout-5.0.1-pyhd8ed1ab_1.conda
https://conda.anaconda.org/conda-forge/noarch/attrs-25.1.0-pyh71513ae_0.conda
https://repo.anaconda.com/pkgs/main/win-64/babel-2.16.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/backcall-0.2.0-pyhd3eb1b0_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/blinker-1.9.0-pyhff2d567_0.conda
https://conda.anaconda.org/conda-forge/win-64/brotli-python-1.1.0-py39ha51f57c_2.conda
https://conda.anaconda.org/conda-forge/noarch/cached_property-1.5.2-pyha770c72_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cachetools-5.5.1-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/win-64/certifi-2025.1.31-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/charset-normalizer-3.4.1-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/colorama-0.4.6-pyhd8ed1ab_1.conda
https://repo.anaconda.com/pkgs/main/win-64/debugpy-1.8.11-py39h5da7b33_0.conda
https://repo.anaconda.com/pkgs/main/noarch/decorator-5.1.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/defusedxml-0.7.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/exceptiongroup-1.2.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/executing-0.8.3-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/win-64/frozenlist-1.5.0-py39hf73967f_1.conda
https://conda.anaconda.org/conda-forge/noarch/gast-0.4.0-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/h11-0.14.0-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/hpack-4.1.0-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/hyperframe-6.1.0-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/idna-3.10-pyhd8ed1ab_1.conda
https://repo.anaconda.com/pkgs/main/win-64/json5-0.9.25-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/jupyterlab_widgets-3.0.13-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/keras-2.10.0-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/markupsafe-3.0.2-py39hf73967f_1.conda
https://repo.anaconda.com/pkgs/main/win-64/mistune-2.0.4-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/nest-asyncio-1.6.0-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/opt_einsum-3.4.0-pyhd8ed1ab_1.conda
https://repo.anaconda.com/pkgs/main/win-64/overrides-7.4.0-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/packaging-24.2-pyhd8ed1ab_2.conda
https://repo.anaconda.com/pkgs/main/noarch/pandocfilters-1.5.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/parso-0.8.4-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pickleshare-0.7.5-pyhd3eb1b0_1003.conda
https://repo.anaconda.com/pkgs/main/win-64/platformdirs-3.10.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/ply-3.11-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/prometheus_client-0.21.0-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/win-64/propcache-0.2.1-py39hf73967f_1.conda
https://repo.anaconda.com/pkgs/main/win-64/psutil-5.9.0-py39h827c3e9_1.conda
https://repo.anaconda.com/pkgs/main/noarch/pure_eval-0.2.2-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/pyasn1-0.6.1-pyhd8ed1ab_2.conda
https://conda.anaconda.org/conda-forge/noarch/pycparser-2.22-pyh29332c3_1.conda
https://repo.anaconda.com/pkgs/main/win-64/pygments-2.15.1-py39haa95532_1.conda
https://conda.anaconda.org/conda-forge/noarch/pyjwt-2.10.1-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pyqt5-sip-12.13.0-py39h827c3e9_1.conda
https://repo.anaconda.com/pkgs/main/win-64/python-fastjsonschema-2.20.0-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/python-flatbuffers-25.2.10-pyhbc23db3_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pywin32-308-py39h5da7b33_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pywinpty-2.0.14-py39h72d21ff_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pyyaml-6.0.2-py39h827c3e9_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pyzmq-26.2.0-py39h5da7b33_0.conda
https://repo.anaconda.com/pkgs/main/win-64/qt-main-5.15.2-h6072711_9.conda
https://repo.anaconda.com/pkgs/main/win-64/rfc3986-validator-0.1.1-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/rpds-py-0.22.3-py39h636fa0f_0.conda
https://repo.anaconda.com/pkgs/main/win-64/send2trash-1.8.2-py39haa95532_1.conda
https://repo.anaconda.com/pkgs/main/win-64/setuptools-75.8.0-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/six-1.17.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/win-64/sniffio-1.3.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/soupsieve-2.5-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/win-64/tbb-2021.13.0-h62715c5_1.conda
https://conda.anaconda.org/conda-forge/win-64/tensorboard-data-server-0.6.1-py39hcbf5309_4.conda
https://conda.anaconda.org/conda-forge/noarch/tensorboard-plugin-wit-1.8.1-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/tensorflow-estimator-2.10.0-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/termcolor-2.5.0-pyhd8ed1ab_1.conda
https://repo.anaconda.com/pkgs/main/win-64/tomli-2.0.1-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/tornado-6.4.2-py39h827c3e9_0.conda
https://repo.anaconda.com/pkgs/main/win-64/traitlets-5.14.3-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/typing_extensions-4.12.2-pyha770c72_1.conda
https://repo.anaconda.com/pkgs/main/noarch/wcwidth-0.2.5-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/webencodings-0.5.1-py39haa95532_1.conda
https://repo.anaconda.com/pkgs/main/win-64/websocket-client-1.8.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/wheel-0.45.1-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/widgetsnbextension-4.0.13-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/win_inet_pton-1.1.0-pyh7428d3b_8.conda
https://conda.anaconda.org/conda-forge/win-64/wrapt-1.17.2-py39ha55e580_0.conda
https://conda.anaconda.org/conda-forge/noarch/zipp-3.21.0-pyhd8ed1ab_1.conda
https://conda.anaconda.org/conda-forge/noarch/aiosignal-1.3.2-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/win-64/anyio-4.6.2-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/asttokens-2.0.5-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/astunparse-1.6.3-pyhd8ed1ab_3.conda
https://repo.anaconda.com/pkgs/main/win-64/async-lru-2.0.4-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/beautifulsoup4-4.12.3-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/bleach-6.2.0-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/cached-property-1.5.2-hd8ed1ab_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/cffi-1.17.1-py39ha55e580_0.conda
https://conda.anaconda.org/conda-forge/noarch/click-8.1.8-pyh7428d3b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/comm-0.2.1-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/google-pasta-0.2.0-pyhd8ed1ab_2.conda
https://conda.anaconda.org/conda-forge/win-64/grpcio-1.48.1-py39hf834a4b_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/h2-4.2.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/win-64/httpcore-1.0.2-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/importlib-metadata-8.6.1-pyha770c72_0.conda
https://repo.anaconda.com/pkgs/main/win-64/jedi-0.19.2-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/jinja2-3.1.5-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/jupyter_core-5.7.2-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/jupyterlab_pygments-0.1.2-py_0.conda
https://repo.anaconda.com/pkgs/main/win-64/matplotlib-inline-0.1.6-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/win-64/mkl-2024.2.2-h66d3029_15.conda
https://repo.anaconda.com/pkgs/main/win-64/pip-25.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/prompt-toolkit-3.0.43-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/pyasn1-modules-0.4.1-pyhd8ed1ab_1.conda
https://conda.anaconda.org/conda-forge/noarch/pysocks-1.7.1-pyh09c184e_7.conda
https://repo.anaconda.com/pkgs/main/win-64/python-dateutil-2.9.0post0-py39haa95532_2.conda
https://repo.anaconda.com/pkgs/main/win-64/python-json-logger-3.2.1-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/pyu2f-0.1.5-pyhd8ed1ab_1.conda
https://repo.anaconda.com/pkgs/main/win-64/qtpy-2.4.1-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/referencing-0.30.2-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/rfc3339-validator-0.1.4-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/rsa-4.9-pyhd8ed1ab_1.conda
https://repo.anaconda.com/pkgs/main/win-64/sip-6.7.12-py39h5da7b33_1.conda
https://repo.anaconda.com/pkgs/main/win-64/terminado-0.17.1-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/tinycss2-1.4.0-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/typing-extensions-4.12.2-hd8ed1ab_1.conda
https://conda.anaconda.org/conda-forge/noarch/werkzeug-3.1.3-pyhd8ed1ab_1.conda
https://repo.anaconda.com/pkgs/main/win-64/argon2-cffi-bindings-21.2.0-py39h827c3e9_1.conda
https://conda.anaconda.org/conda-forge/win-64/cryptography-39.0.0-py39h58e9bdb_0.conda
https://conda.anaconda.org/conda-forge/win-64/h5py-3.9.0-nompi_py39h9c8e182_100.conda
https://repo.anaconda.com/pkgs/main/win-64/httpx-0.27.0-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/importlib_metadata-8.6.1-hd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/win-64/jsonschema-specifications-2023.7.1-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/jupyter_server_terminals-0.4.4-py39haa95532_1.conda
https://conda.anaconda.org/conda-forge/win-64/libblas-3.9.0-28_h576b46c_mkl.conda
https://conda.anaconda.org/conda-forge/noarch/markdown-3.6-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/win-64/multidict-6.1.0-py39hf73967f_1.conda
https://repo.anaconda.com/pkgs/main/noarch/prompt_toolkit-3.0.43-hd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pyqt-5.15.10-py39h5da7b33_1.conda
https://repo.anaconda.com/pkgs/main/noarch/stack_data-0.2.0-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/win-64/zstandard-0.23.0-py39h9bf74da_1.conda
https://repo.anaconda.com/pkgs/main/noarch/argon2-cffi-21.3.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/ipython-8.15.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/jsonschema-4.23.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/jupyter_client-8.6.3-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/win-64/libcblas-3.9.0-28_h7ad3364_mkl.conda
https://conda.anaconda.org/conda-forge/win-64/liblapack-3.9.0-28_hacfb0e4_mkl.conda
https://conda.anaconda.org/conda-forge/noarch/oauthlib-3.2.2-pyhd8ed1ab_1.conda
https://conda.anaconda.org/conda-forge/noarch/pyopenssl-23.2.0-pyhd8ed1ab_1.conda
https://conda.anaconda.org/conda-forge/noarch/urllib3-2.3.0-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/win-64/yarl-1.18.3-py39hf73967f_1.conda
https://conda.anaconda.org/conda-forge/win-64/aiohttp-3.11.12-py39hf73967f_0.conda
https://repo.anaconda.com/pkgs/main/win-64/ipykernel-6.29.5-py39haa95532_1.conda
https://repo.anaconda.com/pkgs/main/win-64/ipywidgets-8.1.5-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/jupyter_events-0.10.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/nbformat-5.10.4-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/requests-2.32.3-pyhd8ed1ab_1.conda
https://conda.anaconda.org/conda-forge/win-64/scipy-1.13.1-py39h1a10956_0.conda
https://conda.anaconda.org/conda-forge/noarch/google-auth-2.38.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/win-64/jupyter_console-6.6.3-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/nbclient-0.8.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/qtconsole-5.6.1-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/requests-oauthlib-2.0.0-pyhd8ed1ab_1.conda
https://conda.anaconda.org/conda-forge/noarch/google-auth-oauthlib-0.4.6-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/nbconvert-7.16.4-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/jupyter_server-2.14.1-py39haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/tensorboard-2.10.1-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jupyter-lsp-2.2.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/jupyterlab_server-2.27.3-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/notebook-shim-0.2.3-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/tensorflow-base-2.10.0-mkl_py39h6a7f48e_0.conda
https://repo.anaconda.com/pkgs/main/win-64/jupyterlab-4.3.4-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/tensorflow-2.10.0-mkl_py39ha510bab_0.conda
https://repo.anaconda.com/pkgs/main/win-64/notebook-7.3.2-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/jupyter-1.1.1-py39haa95532_0.conda
